document.getElementById("a").style.backgroundColor = "green"
document.getElementById("a").style.color = "white"
document.getElementById("b").style.backgroundColor = "red"
document.getElementById("c").style.backgroundColor = "yellow"
document.getElementById("d").style.backgroundColor = "Cyan"
document.getElementById("e").style.backgroundColor = "Magenta"
document.getElementById("f").style.backgroundColor = "Gray"
document.getElementById("g").style.backgroundColor = "Orange"
document.getElementById("h").style.backgroundColor = "Purple"
document.getElementById("i").style.backgroundColor = "Brown"
document.getElementById("j").style.backgroundColor = "Pink"
document.getElementById("k").style.backgroundColor = "Lime"
document.getElementById("l").style.backgroundColor = "Olive"
document.getElementById("m").style.backgroundColor = "Teal"
document.getElementById("n").style.backgroundColor = "Navy"
document.getElementById("n").style.color = "white"
document.getElementById("o").style.backgroundColor = "SlateBlue"
document.getElementById("p").style.backgroundColor = "SkyBlue"
document.getElementById("q").style.backgroundColor = "Salmon"
document.getElementById("r").style.backgroundColor = "RoyalBlue"
document.getElementById("s").style.backgroundColor = "Peru"
document.getElementById("t").style.backgroundColor = "Lavender"
document.getElementById("u").style.backgroundColor = "Gainsboro"
document.getElementById("v").style.backgroundColor = "Beige"
document.getElementById("w").style.backgroundColor = "AntiqueWhite"
document.getElementById("x").style.backgroundColor = "Gold"


// document.getElementsByClassName("container").style.backgroundColor = "black"


